lst= [1, 2, 3, 7, 5, 6, 4, 20, 9, 8, 20, 30]
print(lst.index(9))
lst.pop()
print(lst)
lst.sort()
print(lst)
print(lst[3])
print(max(lst))
print(min(lst))
print(sum(lst))
print(lst[5])
sum = sum(lst)
length = len(lst)
mean = sum/ length
print(mean)
print(len(lst))
lst.append(40)
print(lst)
lst.insert(0,"behi")
print(lst)
lst.remove(1)
print(lst)
lst.reverse()
print(lst)
print(id(lst))
